config/routes.rb
Rails.application.routes.draw do
  get 'bienvenido/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :articulos


	root 'bienvenido#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articulo.rb
class Articulo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController

	def index
		@articulos = Articulo.all 
	end
	def show
		@articulo = Articulo.find(params[:id]) 
	end

	def new
	end

	def create 
		@articulo = Articulo.new(articulo_params)

		@articulo.save 
		redirect_to @articulo
	end

	private 
	def articulo_params
		params.require(:articulo).permit(:titular, :contenido)
	end

end

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/views/articulos/index.html.erb
<h1>Listado de Articulos</h1>

<table>
	<tr>
		<th>Títular</th>
		<th>Contenido</th>
	</tr>
	<% @articulos.each do |articulo| %>
	<tr>
		<td><%= articulo.titular %></td>
		<td><%= articulo.contenido %></td>
	</tr>
	<% end %>
</table>

app/views/articulos/new.html.erb
<h1>Nuevo Articulo</h1>


<%= form_for :articulo, url: articulos_path  do |f| %>

	<p>
		<%= f.label :titular %><br>
		<%= f.text_field :titular %>
	</p>

	<p>
		<%= f.label :contenido %><br>
		<%= f.text_area :contenido %>
	</p>

	<p>
		<%= f.submit %>
	</p>	

<% end %>

app/views/articulos/show.html.erb
<p>
	<strong>Títular : </strong>
	<%= @articulo.titular %>
</p>

<p>
	<strong>Contenido : </strong>
	<%= @articulo.contenido %>
</p>

app/views/bienvenido/index.html.erb
<h1>Bienvenido#index</h1>
<p>Find me in app/views/bienvenido/index.html.erb</p>

<h1>Hola Rails !</h1>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>